workspace:
  aws:
    account_id: 577926707822
    role: ""
    profile: "aspen"
    region: "us-east-1"
  common:
    environment: "prod"
    tags:
      "Module": "EC2/INSTANCE/AIRFLOW"
      "Backup": "enable"

  ec2:
    name: "airflow"
    instance_type: "t3.xlarge"
    keyname: "prod-key"
    disable_api_termination: true
    volume_size: 100
    volume_type: "gp3"
    delete_on_termination: true
    encrypted: true
    monitoring: false